selftests: Run non-default tests
Use quicktest=1 in the main test run to avoid running default timer
tests twice.

diff --git a/debian/tests/selftests b/debian/tests/selftests
--- a/debian/tests/selftests
+++ b/debian/tests/selftests
@@ -44,7 +44,10 @@ if [ "$step" -ge 0 ]; then
 	make headers_install
 
 	# Ignore compiler warnings
-	make -C tools/testing/selftests 2>&1 || echo >&2 "Build failed"
+	{
+	    make -C tools/testing/selftests &&
+	    make -C tools/testing/selftests/memfd build_fuse
+	} 2>&1 || echo >&2 "Build failed"
 
 	# Enable testing CLONE_USERNS by unprivileged users
 	sysctl kernel.unprivileged_userns_clone=1
@@ -53,7 +56,13 @@ if [ "$step" -ge 0 ]; then
 	# and the exit code from make will be 0 even if tests failed.
 	# So we have to do some post-analysis...
 	set -o pipefail
-	make -C tools/testing/selftests run_tests 2>&1 | tee $ADTTMP/log
+	{
+	    make -C tools/testing/selftests quicktest=1 run_tests &&
+	    make -C tools/testing/selftests/cpu-hotplug run_full_test &&
+	    make -C tools/testing/selftests/memory-hotplug run_full_test &&
+	    make -C tools/testing/selftests/memfd run_fuse &&
+	    make -C tools/testing/selftests/timers run_destructive_tests
+	} 2>&1 | tee $ADTTMP/log
 	set +o pipefail
 	if grep -E '\[(FAIL|UNSUPPORTED)\]|recipe for target .run_tests. failed' $ADTTMP/log | \
 	    grep -q -v \
