add the orig target back for development convenience add 2.6.12.3 patch
svn path=/trunk/kernel/source/linux-2.6-2.6.12/; revision=3531

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -194,6 +194,18 @@ debian/build-stamp: debian/unpack-stamp
 	done
 	touch debian/build-stamp
 
+orig: ../orig/linux-$(major)-$(version)
+	rsync --delete --exclude debian --exclude .svn -av ../orig/linux-$(major)-$(version)/ .
+
+../orig/linux-$(major)-$(version):
+	if [ -f "../linux-$(major)_$(version).orig.tar.gz" ]; then \
+		mkdir -p ../orig; \
+		tar -C ../orig -xzf ../linux-$(major)_$(version).orig.tar.gz; \
+	else \
+		echo "Can't find orig tarball." >&2; \
+		exit 1; \
+	fi
+
 clean: unpatch
 	dh_testdir
 	rm -f version.Debian
