Update test-patches to work with a single patch series
svn path=/dists/sid/linux/; revision=19073

diff --git a/debian/bin/test-patches b/debian/bin/test-patches
--- a/debian/bin/test-patches
+++ b/debian/bin/test-patches
@@ -56,10 +56,10 @@ if [ "${version%a~test}" = "$version" ]; then
 fi
 
 restrictfeature=
-series="${version##*-}"
-if [ "$featureset" != none ]; then
-    restrictfeature=" featureset=$featureset"
-    series="${series}-extra"
+if [ "$featureset" = none ]; then
+    series="series-all"
+else
+    series="series-${featureset}"
 fi
 
 # Copy all patches into a new directory
@@ -67,10 +67,13 @@ rm -rf debian/patches/test/
 mkdir debian/patches/test
 cp -t debian/patches/test/ "$@"
 
-# Generate patch series for the new version
->debian/patches/series/"$series"
+# Try to clean up any test patches on exit, but also do it now just in case
+sed -i '/^+ test\//d' debian/patches/"$series"
+trap "sed -i '/^+ test\//d' debian/patches/\"$series\"" EXIT
+
+# Append to patch series
 for patch in "$@"; do
-    echo "+ test/$(basename "$patch")${restrictfeature}" >>debian/patches/series/"$series"
+    echo "+ test/$(basename "$patch")" >>debian/patches/"$series"
 done
 
 # Regenerate control and included rules
